#!/usr/bin/with-contenv sh

if [ -z "$(getent group mopidy)" ]; then
  echo "Creating mopidy group and migrating mopidy user"
  /usr/sbin/addgroup -S mopidy
  /usr/sbin/usermod -g mopidy mopidy
fi

if ! getent group audio | grep -q "\bmopidy\b" ; then
  echo "Adding mopidy to audio group"
  /usr/sbin/adduser mopidy audio
fi

# Setup user/group ids
if [ ! -z "${MOPIDY_UID}" ]; then
  if [ ! "$(id -u mopidy)" -eq "${MOPIDY_UID}" ]; then
    /usr/sbin/usermod -o -u "${MOPIDY_UID}" mopidy
    $ID_CHANGED=true
  fi
fi

if [ ! -z "${MOPIDY_GID}" ]; then
  if [ ! "$(id -g mopidy)" -eq "${MOPIDY_GID}" ]; then
    /usr/sbin/groupmod -o -g "${MOPIDY_GID}" mopidy
    $ID_CHANGED=true
  fi
fi

if [ ! -z "${AUDIO_GID}" ]; then
  if [ ! "$(getent group audio | awk -F: '{printf $3}')" -eq "${AUDIO_GID}" ]; then
    /usr/sbin/groupmod -o -g "${AUDIO_GID}" audio
  fi
fi

if $ID_CHANGED; then
  chown -R mopidy:mopidy /data
fi

